/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ResidentSubmitRequestImport } from './routes/resident/submit-request'
import { Route as ResidentContactImport } from './routes/resident/contact'
import { Route as AdminUnpaidAccountsImport } from './routes/admin/unpaid-accounts'
import { Route as AdminResidentsImport } from './routes/admin/residents'
import { Route as AdminProfileImport } from './routes/admin/profile'
import { Route as AdminNotificationsImport } from './routes/admin/notifications'
import { Route as AdminEmployeesImport } from './routes/admin/employees'
import { Route as AdminEditProfileImport } from './routes/admin/edit-profile'
import { Route as AdminAddResidentImport } from './routes/admin/add-resident'
import { Route as AdminAccountImport } from './routes/admin/account'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AdminFinancialFinancialImport } from './routes/admin/financial/_financial'
import { Route as AdminFinancialFinancialRecordsImport } from './routes/admin/financial/_financial.records'
import { Route as AdminFinancialFinancialMonthlyDueImport } from './routes/admin/financial/_financial.monthly-due'

// Create Virtual Routes

const ResidentRouteLazyImport = createFileRoute('/resident')()
const AdminFinancialImport = createFileRoute('/admin/financial')()
const ResidentUploadPaymentLazyImport = createFileRoute(
  '/resident/upload-payment',
)()
const ResidentProfileLazyImport = createFileRoute('/resident/profile')()
const ResidentPaynowLazyImport = createFileRoute('/resident/paynow')()
const ResidentNoticesLazyImport = createFileRoute('/resident/notices')()
const ResidentInquiriesLazyImport = createFileRoute('/resident/inquiries')()
const ResidentFinancialLazyImport = createFileRoute('/resident/financial')()
const ResidentEditProfileLazyImport = createFileRoute(
  '/resident/edit-profile',
)()
const ResidentDashboardLazyImport = createFileRoute('/resident/dashboard')()
const ResidentAccountLazyImport = createFileRoute('/resident/account')()

// Create/Update Routes

const ResidentRouteLazyRoute = ResidentRouteLazyImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/resident/route.lazy').then((d) => d.Route),
)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminFinancialRoute = AdminFinancialImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const ResidentUploadPaymentLazyRoute = ResidentUploadPaymentLazyImport.update({
  id: '/upload-payment',
  path: '/upload-payment',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/upload-payment.lazy').then((d) => d.Route),
)

const ResidentProfileLazyRoute = ResidentProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/profile.lazy').then((d) => d.Route),
)

const ResidentPaynowLazyRoute = ResidentPaynowLazyImport.update({
  id: '/paynow',
  path: '/paynow',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/paynow.lazy').then((d) => d.Route),
)

const ResidentNoticesLazyRoute = ResidentNoticesLazyImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/notices.lazy').then((d) => d.Route),
)

const ResidentInquiriesLazyRoute = ResidentInquiriesLazyImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/inquiries.lazy').then((d) => d.Route),
)

const ResidentFinancialLazyRoute = ResidentFinancialLazyImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/financial.lazy').then((d) => d.Route),
)

const ResidentEditProfileLazyRoute = ResidentEditProfileLazyImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/edit-profile.lazy').then((d) => d.Route),
)

const ResidentDashboardLazyRoute = ResidentDashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/dashboard.lazy').then((d) => d.Route),
)

const ResidentAccountLazyRoute = ResidentAccountLazyImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/resident/account.lazy').then((d) => d.Route),
)

const ResidentSubmitRequestRoute = ResidentSubmitRequestImport.update({
  id: '/submit-request',
  path: '/submit-request',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any)

const ResidentContactRoute = ResidentContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ResidentRouteLazyRoute,
} as any)

const AdminUnpaidAccountsRoute = AdminUnpaidAccountsImport.update({
  id: '/unpaid-accounts',
  path: '/unpaid-accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminResidentsRoute = AdminResidentsImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProfileRoute = AdminProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminNotificationsRoute = AdminNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminEmployeesRoute = AdminEmployeesImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminEditProfileRoute = AdminEditProfileImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAddResidentRoute = AdminAddResidentImport.update({
  id: '/add-resident',
  path: '/add-resident',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAccountRoute = AdminAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AdminFinancialFinancialRoute = AdminFinancialFinancialImport.update({
  id: '/_financial',
  getParentRoute: () => AdminFinancialRoute,
} as any)

const AdminFinancialFinancialRecordsRoute =
  AdminFinancialFinancialRecordsImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AdminFinancialFinancialRoute,
  } as any)

const AdminFinancialFinancialMonthlyDueRoute =
  AdminFinancialFinancialMonthlyDueImport.update({
    id: '/monthly-due',
    path: '/monthly-due',
    getParentRoute: () => AdminFinancialFinancialRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/add-resident': {
      id: '/admin/add-resident'
      path: '/add-resident'
      fullPath: '/admin/add-resident'
      preLoaderRoute: typeof AdminAddResidentImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/edit-profile': {
      id: '/admin/edit-profile'
      path: '/edit-profile'
      fullPath: '/admin/edit-profile'
      preLoaderRoute: typeof AdminEditProfileImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/unpaid-accounts': {
      id: '/admin/unpaid-accounts'
      path: '/unpaid-accounts'
      fullPath: '/admin/unpaid-accounts'
      preLoaderRoute: typeof AdminUnpaidAccountsImport
      parentRoute: typeof AdminRouteImport
    }
    '/resident/contact': {
      id: '/resident/contact'
      path: '/contact'
      fullPath: '/resident/contact'
      preLoaderRoute: typeof ResidentContactImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/submit-request': {
      id: '/resident/submit-request'
      path: '/submit-request'
      fullPath: '/resident/submit-request'
      preLoaderRoute: typeof ResidentSubmitRequestImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/account': {
      id: '/resident/account'
      path: '/account'
      fullPath: '/resident/account'
      preLoaderRoute: typeof ResidentAccountLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/dashboard': {
      id: '/resident/dashboard'
      path: '/dashboard'
      fullPath: '/resident/dashboard'
      preLoaderRoute: typeof ResidentDashboardLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/edit-profile': {
      id: '/resident/edit-profile'
      path: '/edit-profile'
      fullPath: '/resident/edit-profile'
      preLoaderRoute: typeof ResidentEditProfileLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/financial': {
      id: '/resident/financial'
      path: '/financial'
      fullPath: '/resident/financial'
      preLoaderRoute: typeof ResidentFinancialLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/inquiries': {
      id: '/resident/inquiries'
      path: '/inquiries'
      fullPath: '/resident/inquiries'
      preLoaderRoute: typeof ResidentInquiriesLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/notices': {
      id: '/resident/notices'
      path: '/notices'
      fullPath: '/resident/notices'
      preLoaderRoute: typeof ResidentNoticesLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/paynow': {
      id: '/resident/paynow'
      path: '/paynow'
      fullPath: '/resident/paynow'
      preLoaderRoute: typeof ResidentPaynowLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/profile': {
      id: '/resident/profile'
      path: '/profile'
      fullPath: '/resident/profile'
      preLoaderRoute: typeof ResidentProfileLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/resident/upload-payment': {
      id: '/resident/upload-payment'
      path: '/upload-payment'
      fullPath: '/resident/upload-payment'
      preLoaderRoute: typeof ResidentUploadPaymentLazyImport
      parentRoute: typeof ResidentRouteLazyImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/financial/_financial': {
      id: '/admin/financial/_financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialFinancialImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/_financial/monthly-due': {
      id: '/admin/financial/_financial/monthly-due'
      path: '/monthly-due'
      fullPath: '/admin/financial/monthly-due'
      preLoaderRoute: typeof AdminFinancialFinancialMonthlyDueImport
      parentRoute: typeof AdminFinancialFinancialImport
    }
    '/admin/financial/_financial/records': {
      id: '/admin/financial/_financial/records'
      path: '/records'
      fullPath: '/admin/financial/records'
      preLoaderRoute: typeof AdminFinancialFinancialRecordsImport
      parentRoute: typeof AdminFinancialFinancialImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminFinancialFinancialRouteChildren {
  AdminFinancialFinancialMonthlyDueRoute: typeof AdminFinancialFinancialMonthlyDueRoute
  AdminFinancialFinancialRecordsRoute: typeof AdminFinancialFinancialRecordsRoute
}

const AdminFinancialFinancialRouteChildren: AdminFinancialFinancialRouteChildren =
  {
    AdminFinancialFinancialMonthlyDueRoute:
      AdminFinancialFinancialMonthlyDueRoute,
    AdminFinancialFinancialRecordsRoute: AdminFinancialFinancialRecordsRoute,
  }

const AdminFinancialFinancialRouteWithChildren =
  AdminFinancialFinancialRoute._addFileChildren(
    AdminFinancialFinancialRouteChildren,
  )

interface AdminFinancialRouteChildren {
  AdminFinancialFinancialRoute: typeof AdminFinancialFinancialRouteWithChildren
}

const AdminFinancialRouteChildren: AdminFinancialRouteChildren = {
  AdminFinancialFinancialRoute: AdminFinancialFinancialRouteWithChildren,
}

const AdminFinancialRouteWithChildren = AdminFinancialRoute._addFileChildren(
  AdminFinancialRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAddResidentRoute: typeof AdminAddResidentRoute
  AdminEditProfileRoute: typeof AdminEditProfileRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminUnpaidAccountsRoute: typeof AdminUnpaidAccountsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinancialRoute: typeof AdminFinancialRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAddResidentRoute: AdminAddResidentRoute,
  AdminEditProfileRoute: AdminEditProfileRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminUnpaidAccountsRoute: AdminUnpaidAccountsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinancialRoute: AdminFinancialRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ResidentRouteLazyRouteChildren {
  ResidentContactRoute: typeof ResidentContactRoute
  ResidentSubmitRequestRoute: typeof ResidentSubmitRequestRoute
  ResidentAccountLazyRoute: typeof ResidentAccountLazyRoute
  ResidentDashboardLazyRoute: typeof ResidentDashboardLazyRoute
  ResidentEditProfileLazyRoute: typeof ResidentEditProfileLazyRoute
  ResidentFinancialLazyRoute: typeof ResidentFinancialLazyRoute
  ResidentInquiriesLazyRoute: typeof ResidentInquiriesLazyRoute
  ResidentNoticesLazyRoute: typeof ResidentNoticesLazyRoute
  ResidentPaynowLazyRoute: typeof ResidentPaynowLazyRoute
  ResidentProfileLazyRoute: typeof ResidentProfileLazyRoute
  ResidentUploadPaymentLazyRoute: typeof ResidentUploadPaymentLazyRoute
}

const ResidentRouteLazyRouteChildren: ResidentRouteLazyRouteChildren = {
  ResidentContactRoute: ResidentContactRoute,
  ResidentSubmitRequestRoute: ResidentSubmitRequestRoute,
  ResidentAccountLazyRoute: ResidentAccountLazyRoute,
  ResidentDashboardLazyRoute: ResidentDashboardLazyRoute,
  ResidentEditProfileLazyRoute: ResidentEditProfileLazyRoute,
  ResidentFinancialLazyRoute: ResidentFinancialLazyRoute,
  ResidentInquiriesLazyRoute: ResidentInquiriesLazyRoute,
  ResidentNoticesLazyRoute: ResidentNoticesLazyRoute,
  ResidentPaynowLazyRoute: ResidentPaynowLazyRoute,
  ResidentProfileLazyRoute: ResidentProfileLazyRoute,
  ResidentUploadPaymentLazyRoute: ResidentUploadPaymentLazyRoute,
}

const ResidentRouteLazyRouteWithChildren =
  ResidentRouteLazyRoute._addFileChildren(ResidentRouteLazyRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/resident': typeof ResidentRouteLazyRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/add-resident': typeof AdminAddResidentRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/unpaid-accounts': typeof AdminUnpaidAccountsRoute
  '/resident/contact': typeof ResidentContactRoute
  '/resident/submit-request': typeof ResidentSubmitRequestRoute
  '/resident/account': typeof ResidentAccountLazyRoute
  '/resident/dashboard': typeof ResidentDashboardLazyRoute
  '/resident/edit-profile': typeof ResidentEditProfileLazyRoute
  '/resident/financial': typeof ResidentFinancialLazyRoute
  '/resident/inquiries': typeof ResidentInquiriesLazyRoute
  '/resident/notices': typeof ResidentNoticesLazyRoute
  '/resident/paynow': typeof ResidentPaynowLazyRoute
  '/resident/profile': typeof ResidentProfileLazyRoute
  '/resident/upload-payment': typeof ResidentUploadPaymentLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/financial': typeof AdminFinancialFinancialRouteWithChildren
  '/admin/financial/monthly-due': typeof AdminFinancialFinancialMonthlyDueRoute
  '/admin/financial/records': typeof AdminFinancialFinancialRecordsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/resident': typeof ResidentRouteLazyRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/add-resident': typeof AdminAddResidentRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/unpaid-accounts': typeof AdminUnpaidAccountsRoute
  '/resident/contact': typeof ResidentContactRoute
  '/resident/submit-request': typeof ResidentSubmitRequestRoute
  '/resident/account': typeof ResidentAccountLazyRoute
  '/resident/dashboard': typeof ResidentDashboardLazyRoute
  '/resident/edit-profile': typeof ResidentEditProfileLazyRoute
  '/resident/financial': typeof ResidentFinancialLazyRoute
  '/resident/inquiries': typeof ResidentInquiriesLazyRoute
  '/resident/notices': typeof ResidentNoticesLazyRoute
  '/resident/paynow': typeof ResidentPaynowLazyRoute
  '/resident/profile': typeof ResidentProfileLazyRoute
  '/resident/upload-payment': typeof ResidentUploadPaymentLazyRoute
  '/admin': typeof AdminIndexRoute
  '/admin/financial': typeof AdminFinancialFinancialRouteWithChildren
  '/admin/financial/monthly-due': typeof AdminFinancialFinancialMonthlyDueRoute
  '/admin/financial/records': typeof AdminFinancialFinancialRecordsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/resident': typeof ResidentRouteLazyRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/add-resident': typeof AdminAddResidentRoute
  '/admin/edit-profile': typeof AdminEditProfileRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/unpaid-accounts': typeof AdminUnpaidAccountsRoute
  '/resident/contact': typeof ResidentContactRoute
  '/resident/submit-request': typeof ResidentSubmitRequestRoute
  '/resident/account': typeof ResidentAccountLazyRoute
  '/resident/dashboard': typeof ResidentDashboardLazyRoute
  '/resident/edit-profile': typeof ResidentEditProfileLazyRoute
  '/resident/financial': typeof ResidentFinancialLazyRoute
  '/resident/inquiries': typeof ResidentInquiriesLazyRoute
  '/resident/notices': typeof ResidentNoticesLazyRoute
  '/resident/paynow': typeof ResidentPaynowLazyRoute
  '/resident/profile': typeof ResidentProfileLazyRoute
  '/resident/upload-payment': typeof ResidentUploadPaymentLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/financial': typeof AdminFinancialRouteWithChildren
  '/admin/financial/_financial': typeof AdminFinancialFinancialRouteWithChildren
  '/admin/financial/_financial/monthly-due': typeof AdminFinancialFinancialMonthlyDueRoute
  '/admin/financial/_financial/records': typeof AdminFinancialFinancialRecordsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/login'
    | '/resident'
    | '/dashboard'
    | '/admin/account'
    | '/admin/add-resident'
    | '/admin/edit-profile'
    | '/admin/employees'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/residents'
    | '/admin/unpaid-accounts'
    | '/resident/contact'
    | '/resident/submit-request'
    | '/resident/account'
    | '/resident/dashboard'
    | '/resident/edit-profile'
    | '/resident/financial'
    | '/resident/inquiries'
    | '/resident/notices'
    | '/resident/paynow'
    | '/resident/profile'
    | '/resident/upload-payment'
    | '/admin/'
    | '/admin/financial'
    | '/admin/financial/monthly-due'
    | '/admin/financial/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/resident'
    | '/dashboard'
    | '/admin/account'
    | '/admin/add-resident'
    | '/admin/edit-profile'
    | '/admin/employees'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/residents'
    | '/admin/unpaid-accounts'
    | '/resident/contact'
    | '/resident/submit-request'
    | '/resident/account'
    | '/resident/dashboard'
    | '/resident/edit-profile'
    | '/resident/financial'
    | '/resident/inquiries'
    | '/resident/notices'
    | '/resident/paynow'
    | '/resident/profile'
    | '/resident/upload-payment'
    | '/admin'
    | '/admin/financial'
    | '/admin/financial/monthly-due'
    | '/admin/financial/records'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/admin'
    | '/login'
    | '/resident'
    | '/_auth/dashboard'
    | '/admin/account'
    | '/admin/add-resident'
    | '/admin/edit-profile'
    | '/admin/employees'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/residents'
    | '/admin/unpaid-accounts'
    | '/resident/contact'
    | '/resident/submit-request'
    | '/resident/account'
    | '/resident/dashboard'
    | '/resident/edit-profile'
    | '/resident/financial'
    | '/resident/inquiries'
    | '/resident/notices'
    | '/resident/paynow'
    | '/resident/profile'
    | '/resident/upload-payment'
    | '/admin/'
    | '/admin/financial'
    | '/admin/financial/_financial'
    | '/admin/financial/_financial/monthly-due'
    | '/admin/financial/_financial/records'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResidentRouteLazyRoute: typeof ResidentRouteLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResidentRouteLazyRoute: ResidentRouteLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/admin",
        "/login",
        "/resident"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/dashboard"
      ]
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/account",
        "/admin/add-resident",
        "/admin/edit-profile",
        "/admin/employees",
        "/admin/notifications",
        "/admin/profile",
        "/admin/residents",
        "/admin/unpaid-accounts",
        "/admin/",
        "/admin/financial"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/resident": {
      "filePath": "resident/route.lazy.tsx",
      "children": [
        "/resident/contact",
        "/resident/submit-request",
        "/resident/account",
        "/resident/dashboard",
        "/resident/edit-profile",
        "/resident/financial",
        "/resident/inquiries",
        "/resident/notices",
        "/resident/paynow",
        "/resident/profile",
        "/resident/upload-payment"
      ]
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/admin/account": {
      "filePath": "admin/account.tsx",
      "parent": "/admin"
    },
    "/admin/add-resident": {
      "filePath": "admin/add-resident.tsx",
      "parent": "/admin"
    },
    "/admin/edit-profile": {
      "filePath": "admin/edit-profile.tsx",
      "parent": "/admin"
    },
    "/admin/employees": {
      "filePath": "admin/employees.tsx",
      "parent": "/admin"
    },
    "/admin/notifications": {
      "filePath": "admin/notifications.tsx",
      "parent": "/admin"
    },
    "/admin/profile": {
      "filePath": "admin/profile.tsx",
      "parent": "/admin"
    },
    "/admin/residents": {
      "filePath": "admin/residents.tsx",
      "parent": "/admin"
    },
    "/admin/unpaid-accounts": {
      "filePath": "admin/unpaid-accounts.tsx",
      "parent": "/admin"
    },
    "/resident/contact": {
      "filePath": "resident/contact.tsx",
      "parent": "/resident"
    },
    "/resident/submit-request": {
      "filePath": "resident/submit-request.tsx",
      "parent": "/resident"
    },
    "/resident/account": {
      "filePath": "resident/account.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/dashboard": {
      "filePath": "resident/dashboard.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/edit-profile": {
      "filePath": "resident/edit-profile.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/financial": {
      "filePath": "resident/financial.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/inquiries": {
      "filePath": "resident/inquiries.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/notices": {
      "filePath": "resident/notices.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/paynow": {
      "filePath": "resident/paynow.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/profile": {
      "filePath": "resident/profile.lazy.tsx",
      "parent": "/resident"
    },
    "/resident/upload-payment": {
      "filePath": "resident/upload-payment.lazy.tsx",
      "parent": "/resident"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/financial": {
      "filePath": "admin/financial",
      "parent": "/admin",
      "children": [
        "/admin/financial/_financial"
      ]
    },
    "/admin/financial/_financial": {
      "filePath": "admin/financial/_financial.tsx",
      "parent": "/admin/financial",
      "children": [
        "/admin/financial/_financial/monthly-due",
        "/admin/financial/_financial/records"
      ]
    },
    "/admin/financial/_financial/monthly-due": {
      "filePath": "admin/financial/_financial.monthly-due.tsx",
      "parent": "/admin/financial/_financial"
    },
    "/admin/financial/_financial/records": {
      "filePath": "admin/financial/_financial.records.tsx",
      "parent": "/admin/financial/_financial"
    }
  }
}
ROUTE_MANIFEST_END */
